# Generated by Django 3.1.3 on 2020-11-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_nr', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
                ('telephone_number', models.CharField(max_length=15)),
                ('number_of_opinions', models.IntegerField(default=0)),
                ('avg_opinion', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
