# Generated by Django 3.1.3 on 2020-11-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='auction',
            name='is_shipping_av',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user_highest_bid',
            field=models.IntegerField(blank=True),
        ),
    ]
