# Generated by Django 3.1.3 on 2020-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201121_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='user_highest_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
