# Generated by Django 3.1.3 on 2020-12-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
