# Generated by Django 3.1.3 on 2020-12-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201202_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='profileAvatar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avg_opinion',
            new_name='profileAvgOpinion',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bank_account_nr',
            new_name='profileBankAccountNr',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='number_of_opinions',
            new_name='profileNumberOfOpinions',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telephone_number',
            new_name='profileTelephoneNumber',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profileUser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileUserName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileUserSurame',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
