# Generated by Django 3.1.4 on 2020-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201204_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileAvatar',
            field=models.ImageField(blank=True, default='../media/default.jpg', null=True, upload_to=''),
        ),
    ]
