# Generated by Django 3.1.4 on 2020-12-05 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_message_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='messageContent',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='messageCreatedAt',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted',
            new_name='messageIsDeleted',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated_at',
            new_name='messageUpdatedAt',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='from_user',
            new_name='usermessFromUser',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='is_deleted',
            new_name='usermessIsDeleted',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='message',
            new_name='usermessMessage',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='to_user',
            new_name='usermessToUser',
        ),
    ]
