# Generated by Django 3.1.4 on 2020-12-08 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201208_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropinion',
            name='opinionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
