# Generated by Django 3.1.4 on 2020-12-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_useropinion_opiniondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileAvgOpinion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileNumberOfOpinions',
        ),
    ]
