# Generated by Django 3.1.4 on 2020-12-10 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0026_auto_20201210_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportContent', models.TextField(blank=True, null=True)),
                ('reportAuction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auction')),
                ('reportUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
