# Generated by Django 3.1.4 on 2020-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auctionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionShippingCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
