# Generated by Django 3.1.4 on 2020-12-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201221_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dm2tx6lhe/image/upload/v1608590488/media/images/default_auction_fe1wvk.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileAvatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dm2tx6lhe/image/upload/v1608653722/media/images/default_d19dbf.jpg', null=True, upload_to='images/'),
        ),
    ]
