# Generated by Django 3.1.4 on 2020-12-28 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0030_auto_20201228_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='date_end',
            new_name='auctionDateEnd',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='date_started',
            new_name='auctionDateStarted',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='description',
            new_name='auctionDescription',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='highest_bid',
            new_name='auctionHighestBid',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='image',
            new_name='auctionImage',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='is_active',
            new_name='auctionIsActive',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='is_new',
            new_name='auctionIsNew',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='is_shipping_av',
            new_name='auctionIsShippingAv',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='minimal_price',
            new_name='auctionMinimalPrice',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='product_name',
            new_name='auctionProductName',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='starting_price',
            new_name='auctionStartingPrice',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='user_highest_bid',
            new_name='auctionUserHighestBid',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='category',
            new_name='auctionCategory',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='user_seller',
            new_name='auctionUserSeller',
        ),
    ]
