# Generated by Django 3.1.4 on 2021-01-01 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0031_auto_20201228_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileBankAccountNr',
        ),
    ]
